config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "pages#landing"
  get "auth", to: "pages#auth"
  get "dashboard", to: "pages#dashboard"

  resources :concerts do
    resources :contents do
      resources :votes, only: %i[create destroy update]
      resources :reviews, only: %i[create destroy new update]
    end
    resources :participations, only: %i[create destroy]
  end
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :concert
  belongs_to :user
  has_many :reviews, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :users, through: :votes
  validates :title, presence: true
  has_one_attached :video
  has_one_attached :image

  def upvotes_count
    votes.where(value: 1).count
  end


  def downvotes_count
    votes.where(value: -1).count
  end

  def score
    upvotes_count - downvotes_count
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  before_action :set_concert, only: %i[index show new create edit update destroy]
  before_action :set_content, only: %i[edit update destroy]

  def index
    @contents = @concert.contents
  end

  def show
    @content = Content.find(params[:id])
    @concert = @content.concert
  end

  def new
    @content = Content.new
  end

  def create
    @content = @concert.contents.new(content_params)
    @content.user = current_user
    @content.save
    redirect_to concert_path(@concert)
  end

  def edit; end

  def update
    @content.update(content_params)
    redirect_to dashboard_path
  end

  def destroy
    @content.destroy
    redirect_to dashboard_path
  end

  private

  def set_concert
    @concert = Concert.find(params[:concert_id])
  end

  def set_content
    @content = @concert.contents.find(params[:id])
  end

  def content_params
    params.require(:content).permit(:title, :description, :concert_id, :user_id, :image, :video)
  end
end

app/views/contents/edit.html.erb
<div class="container">
  <%= link_to concerts_path, class: "back-button" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <div class="mt-5 pt-4">
    <h1 style="color: white">Modifier mon contenu</h1>
      <%= simple_form_for [@concert, @content] do |f| %>
      <%= f.input :title, label: "Titre" %>
      <%= f.input :description, label: "Mots-clés" %>
      <%= f.input :image, as: :file, label: "Image de l'événement" %>
      <%= f.input :video, as: :file, label: "Vidéo de l'événement" %>
      <%= f.submit "Modifier", class: "form_btn" %>
    <% end %>
  </div>
</div>

app/views/contents/index.html.erb
<h1>liste des contenus</h1>

<% @contents.each do |content| %>
  <%= content.title %>
<% end %>

app/views/contents/new.html.erb
<div class="container">
  <%= link_to concerts_path, class: "back-button" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <div class="mt-5 pt-4">
    <h1 style="color: white">Ajouter du contenu</h1>
      <%= simple_form_for [@concert, @content] do |f| %>
      <%= f.input :title, label: "Titre" %>
      <%= f.input :description, label: "Mots-clés" %>
      <%= f.input :image, as: :file, label: "Image de l'événement" %>
      <%= f.input :video, as: :file, label: "Vidéo de l'événement" %>
      <%= f.submit "Ajouter", class: "form_btn" %>
    <% end %>
  </div>
</div>

app/views/contents/show.html.erb
<div class="container-fluid p-0 d-flex flex-column justify-content-between vh-100">
  <%= link_to concert_path(@concert), class: "back-button" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>

  <div class="image-container position-relative d-flex flex-column align-items-center flex-grow-1">
    <% if @content.image.attached? %>
      <%= cl_image_tag @content.image.key, class: "content-image" %>
      <%= link_to cl_image_path(@content.image.key, flags: "attachment"), download: "image.jpg", class: "download-button" do %>
        <i class="fa-solid fa-cloud-arrow-down"></i>
      <% end %>
    <% elsif @content.video.attached? %>
      <video controls class="content-video">
        <source src="<%= cl_video_path(@content.video.key) %>" type="video/mp4">
        Votre navigateur ne supporte pas la lecture de vidéos.
      </video>
      <%= link_to cl_video_path(@content.video.key, flags: "attachment"), download: "video.mp4", class: "download-button" do %>
        <i class="fa-solid fa-cloud-arrow-down"></i>
      <% end %>
    <% else %>
      <p class="text-center">Aucune image ou vidéo disponible.</p>
    <% end %>

    <div class="overlay-buttons" data-controller="vote" data-content-id="<%= @content.id %>">
      <button data-action="click->vote#upvote"
              data-vote-target="upvoteButton"
              class="btn btn-lg <%= 'active' if current_user&.voted?(@content, 1) %>">
        <i class="fa-solid fa-thumbs-up" style="color: #9bea99"></i>
        <span data-vote-target="upvoteCount"><%= @content.upvotes_count %></span>
      </button>

      <button class="btn btn-primary btn-lg" data-bs-toggle="offcanvas" data-bs-target="#commentsOffcanvas" aria-controls="commentsOffcanvas">
        <i class="fa-solid fa-comment"></i>
        <span class="comment-counter"><%= @content.reviews.count %></span>
      </button>

      <button data-action="click->vote#downvote"
              data-vote-target="downvoteButton"
              class="btn btn-lg <%= 'active' if current_user&.voted?(@content, -1) %>">
        <i class="fa-solid fa-thumbs-down" style="color: #f57f7f"></i>
        <span data-vote-target="downvoteCount"><%= @content.downvotes_count %></span>
      </button>
    </div>
  </div>
</div>

<div class="offcanvas offcanvas-bottom" tabindex="-1" id="commentsOffcanvas" aria-labelledby="commentsOffcanvasLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="commentsOffcanvasLabel">Commentaires</h5>
    <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div class="reviews-section">
      <% if @content.reviews.any? %>
        <% @content.reviews.each do |review| %>
          <div class="review mb-3 p-3 border rounded">
            <p><strong><%= review.user.username %></strong> a écrit :</p>
            <p><%= review.comment %></p>
            <small>Posté le <%= review.created_at.strftime("%d/%m/%Y à %H:%M") %></small>
          </div>
        <% end %>
      <% else %>
        <p>Aucun commentaire pour le moment. Soyez le premier à commenter !</p>
      <% end %>
    </div>

    <div class="add-comment-section mt-4">
      <%= form_with(model: [@concert, @content, Review.new], url: concert_content_reviews_path(@concert, @content), local: true) do |form| %>
        <div class="mb-3">
          <%= form.label :comment, "Votre commentaire", class: "form-label" %>
          <%= form.text_area :comment, class: "form-control", placeholder: "Écrivez votre commentaire...", rows: 3 %>
        </div>
        <%= form.submit "Envoyer", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>