config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  root "pages#landing"
  get "auth", to: "pages#auth"
  get "dashboard", to: "pages#dashboard"

  resources :concerts do
    resources :contents do
      resources :votes, only: %i[create destroy update]
      resources :reviews, only: %i[create destroy new update]
    end
    resources :participations, only: %i[create destroy]
  end
end

app/models/concert.rb
class Concert < ApplicationRecord
  belongs_to :user
  has_many :contents, dependent: :destroy
  has_many :participations, dependent: :destroy
  has_many :users, through: :participations
  validates :title, presence: true
  validates :description, presence: true
  validates :genre, presence: true
  validates :date, presence: true
  validates :localisation, presence: true
  validates :public, presence: true
  validates :venue, presence: true
  has_one_attached :image
  has_one_attached :video
end

app/controllers/concerts_controller.rb
class ConcertsController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index]
  before_action :set_concert, only: %i[show edit update destroy]

  def index
    @concerts = Concert.all

    if params[:search].present?
      search_term = "%#{params[:search].downcase}%"
      @concerts = @concerts.where(
        "LOWER(title) LIKE ? OR LOWER(description) LIKE ? OR LOWER(localisation) LIKE ? OR LOWER(genre) LIKE ? OR LOWER(venue) LIKE ?",
        search_term, search_term, search_term, search_term, search_term
      )
    end

    if params[:location].present? && params[:location] != "Tous"
      location_term = "%#{params[:location].downcase.strip}%"
      @concerts = @concerts.where("LOWER(localisation) LIKE ?", location_term)
    end

    if params[:style].present? && params[:style] != "Tous"
      @concerts = @concerts.where("LOWER(genre) LIKE ?", "%#{params[:style].downcase}%")
    end

    if params[:date_range].present? && params[:date_range] != "Tous"
      case params[:date_range]
      when "Cette semaine"
        @concerts = @concerts.where(date: Date.today..Date.today + 7.days)
      when "Ce mois"
        @concerts = @concerts.where(date: Date.today..Date.today.end_of_month)
      when "Prochain mois"
        next_month_start = Date.today.next_month.beginning_of_month
        next_month_end = Date.today.next_month.end_of_month
        @concerts = @concerts.where(date: next_month_start..next_month_end)
      when "À venir"
        @concerts = @concerts.where("date >= ?", Date.today)
      end
    end

    @concerts = @concerts.order(date: :desc)

    puts "Concerts: #{@concerts.count}"
  end

  def show
    @contents = @concert.contents.includes(:votes).sort_by { |content| -content.upvotes_count }
  end

  def new
    @concert = Concert.new
  end

  def create
    @concert = Concert.new(concert_params)
    @concert.user = current_user
    if @concert.save
      redirect_to concert_path(@concert)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit; end

  def update
    if @concert.update(concert_params)
      redirect_to concert_path(@concert)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @concert.destroy
    redirect_to concerts_path
  end

  private

  def set_concert
    @concert = Concert.find(params[:id])
  end

  def concert_params
    params.require(:concert).permit(:title, :date, :localisation, :description, :genre, :public, :venue, :image, :user_id, :video)
  end
end

app/views/concerts/edit.html.erb
<div class="container">
  <%= link_to concerts_path, class: "back-button" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <div class="mt-5 pt-4">
    <h1 style="color: white">Modifier le concert</h1>
      <%= simple_form_for [@concert] do |f| %>
      <%= f.input :title, label: "Titre du concert", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :description, label: "Description", class: "form-control rounded-3 d-inline-block" %>
      <div class="d-flex gap-3">
        <div class="w-50">
          <%= f.input :genre,
                      collection: %w(Ambiant Classique Electro Jazz Kpop Metal Multi Pop R&B Reggae Rap Rock Variété),
                      label: "Genre musical",
                      class: "form-control rounded-3 d-inline-block" %>
        </div>
        <div class="w-50">
          <%= f.input :date,
                      as: :string,
                              input_html: {
                                data: { controller: "datepicker" },
                                class: "form-control rounded-3 d-inline-block",
                                label: "Date du concert",
                              } %>
        </div>
      </div>
      <%= f.input :localisation, label: "Ville", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :public, label: "Nombre de participants", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :venue, label: "Salle de concert", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :image, as: :file, label: "Image de l'événement", class: "form-control rounded-3 d-inline-block" %>
      <%= f.submit "Modifier", class: "form_btn" %>
    <% end %>
  </div>
</div>

app/views/concerts/index.html.erb
<div class="home-container">
  <main>
  <div class="d-flex justify-content-between align-items-center w-100 mb-3">
    <% if user_signed_in? %>
        <h1 class="mb-0">Hello, <%= current_user.username %> !</h1>
        <%= link_to dashboard_path do %>
          <% if current_user.avatar.attached? %>
            <%= cl_image_tag current_user.avatar.key, width: 150, height: 150, crop: :fill, class: "avatar ms-3" %>
          <% elsif ["avatar1.JPG", "avatar2.JPG", "avatar3.JPG", "avatar4.JPG", "avatar5.JPG"].include?(current_user.avatar) %>
            <%= image_tag asset_path("avatars/#{current_user.avatar}"), class: "avatar ms-3" %>
          <% else %>
            <div class="avatar-letter ms-3">
              <%= current_user.username[0] %>
            </div>
          <% end %>
        <% end %>
    <% else %>
      <h1 class="mb-3">Bienvenue !</h1>
    <% end %>
  </div>

    <div class="search-bar">
      <%= form_with url: concerts_path, method: :get, local: true, class: "search-form", id: "search-form" do %>
        <%= text_field_tag :search, params[:search], placeholder: "Concert, artiste, lieu, style, date", class: "search-input", id: "search-input" %>
        <%= button_tag "✖", type: "button", class: "clear-search", id: "clear-search" %>
      <% end %>
    </div>


    <div class="location-filter">
    <div class="location">
  </div>
    <div class="filters">
      <%= form_with url: concerts_path, method: :get, local: true, class: "filter-form d-flex align-items-center justify-content-between gap-2" do %>
        <%= hidden_field_tag :location, params[:location].presence || "Paris" %>
          <%= select_tag :style, options_for_select(["Tous", "Indie Rock", "Pop", "Electro", "Rock"], params[:style].presence || "Tous"), class: "filter-select" %>
          <%= select_tag :date_range, options_for_select(["Tous", "Cette semaine", "Ce mois", "Prochain mois"], params[:date_range].presence || "Tous"), class: "filter-select" %>
          <%= submit_tag "Filtrer", class: "filter-submit" %>
      <% end %>
    </div>
    <section class="upcoming-events">
      <% if @concerts.any? %>
        <% @concerts.each do |concert| %>
          <div class="event-row">
            <div class="event-date">
              <span class="day"><%= concert.date.day %></span>
              <span class="month"><%= mois_en_francais(concert.date) %></span>
              <span class="year"><%= concert.date.year %></span>
            </div>
            <%= link_to concert_path(concert), class: "event-card-link" do %>
              <div class="event-card">
                <div class="event-image">
                  <% if concert.image.attached? %>
                    <%= cl_image_tag concert.image.key, width: 300, height: 150, crop: :fill, class: "event-img" %>
                  <% else %>
                    <%= image_tag "Beyoncé.jpg", alt: concert.title, width: 300, height: 150, class: "event-img" %>
                  <% end %>
                </div>
                <div class="event-details">
                  <h3><%= concert.title %></h3>
                  <p>
                    <span class="style">🎵 <%= concert.genre %></span>
                    <span class="venue">🏟 <%= concert.venue %></span>
                  </p>
                  <p class="description" style="text-align: justify"><%= concert.description %></p>
                  <p class="location" style="font-size: 12px">📍 <%= concert.localisation %> 👥 <%= concert.public %></p>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>
      <% else %>
        <p>Aucun concert à venir pour le moment.</p>
      <% end %>
    </section>
    <% if user_signed_in? %>
      <%= link_to new_concert_path do %>
        <i class="fa-solid fa-plus add_concert_btn"></i>
      <% end %>
      <%= link_to "Déconnexion", destroy_user_session_path, data: { turbo_method: :delete }, class: "link" %>
    <% else %>
      <%= link_to "Retour", root_path, class: "link" %>
    <% end %>
    </div>
  </main>
</div>

app/views/concerts/new.html.erb
<div class="container">
  <%= link_to concerts_path, class: "back-button" do %>
    <i class="fa-solid fa-arrow-left"></i>
  <% end %>
  <div class="mt-5 pt-4">
    <h1 style="color: white">Ajouter un concert</h1>
      <%= simple_form_for [@concert] do |f| %>
      <%= f.input :title, label: "Titre du concert", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :description, label: "Description", class: "form-control rounded-3 d-inline-block" %>
      <div class="d-flex gap-3">
        <div class="w-50">
          <%= f.input :genre,
                      collection: %w(Ambiant Classique Electro Jazz Kpop Metal Multi Pop R&B Reggae Rap Rock Variété),
                      label: "Genre musical",
                      class: "form-control rounded-3 d-inline-block" %>
        </div>
        <div class="w-50">
          <%= f.input :date,
                      as: :string,
                              input_html: {
                                data: { controller: "datepicker" },
                                class: "form-control rounded-3 d-inline-block",
                                label: "Date du concert",
                              } %>
        </div>
      </div>
      <%= f.input :localisation, label: "Ville", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :public, label: "Nombre de participants", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :venue, label: "Salle de concert", class: "form-control rounded-3 d-inline-block" %>
      <%= f.input :image, as: :file, label: "Image de l'événement", class: "form-control rounded-3 d-inline-block" %>
      <%= f.submit "Ajouter", class: "form_btn" %>
    <% end %>
  </div>
</div>

app/views/concerts/show.html.erb
<div class="page-container">
  <div class="concert-hero">
    <%= link_to concerts_path, class: "back-button" do %>
      <i class="fa-solid fa-arrow-left"></i>
    <% end %>

    <div class="concert-image">
      <%= cl_image_tag @concert.image.key %>
    </div>

    <div class="concert-info">
      <div class="concert-info-content">
        <div class="concert-details">
          <p class="concert-date">
            <%= @concert.date.strftime("%d/%m/%Y") %>

            <% if user_signed_in? %>
              <% if current_user.attended_concerts.include?(@concert) %>
                <%= link_to "J'y suis allé 🙂", concert_participation_path(@concert),
                            data: { turbo_method: :delete }, class: "participate-button btn-participate" %>
              <% else %>
                <%= link_to "Je n'y suis pas allé 🙁", concert_participations_path(@concert),
                            data: { turbo_method: :post }, class: "participate-button btn-unparticipate" %>
              <% end %>
            <% end %>
          </p>
          <h1 class="concert-title artist"><%= @concert.title %></h1>
          <p class="concert-location"><%= @concert.venue %>, <%= @concert.localisation %></p>
        </div>

        <div class="concert-stats">
          <p class="content-count"><%= @concert.contents.count %>  📷  /  🎥 </p>
        </div>
      </div>
    </div>
  </div>

  <div class="concert-contents-section">
    <div class="content-column-left">
      <% @contents.each_with_index do |content, index| %>
        <div class="media-item">
          <% if index.even? %>
            <% if content.image.attached? %>
              <%= link_to concert_content_path(@concert, content) do %>
                <%= cl_image_tag content.image.key, class: "small-media" %>
              <% end %>
            <% elsif content.video.attached? %>
              <%= link_to concert_content_path(@concert, content) do %>
                <div class="video-wrapper">
                  <video autoplay loop muted class="small-media">
                    <source src="<%= cl_video_path(content.video.key) %>" type="video/mp4">
                    Votre navigateur ne supporte pas la lecture de vidéos.
                  </video>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>

    <div class="content-column-right">
      <% @contents.each_with_index do |content, index| %>
        <div class="media-item">
          <% if index.odd? %>
            <% if content.image.attached? %>
              <%= link_to concert_content_path(@concert, content) do %>
                <%= cl_image_tag content.image.key, class: "small-media" %>
              <% end %>
            <% elsif content.video.attached? %>
              <%= link_to concert_content_path(@concert, content) do %>
                <div class="video-wrapper">
                  <video autoplay loop muted class="small-media">
                    <source src="<%= cl_video_path(content.video.key) %>" type="video/mp4">
                    Votre navigateur ne supporte pas la lecture de vidéos.
                  </video>
                </div>
              <% end %>
            <% end %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="add-content-button">
    <%= link_to new_concert_content_path(@concert), class: "add-button" do %>
      <i class="fa-solid fa-image"></i>
    <% end %>
  </div>
</div>